# Generated by Django 5.1.3 on 2024-12-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_desc_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('PhoneNo', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
