# Generated by Django 5.1.3 on 2024-12-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message_id',
            new_name='msg_id',
        ),
    ]
