# Generated by Django 5.1.3 on 2024-12-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='Order_id',
        ),
    ]
